/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdministracionRouteImport } from './routes/_authenticated/administracion'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedFotografiasRouteImport } from './routes/_authenticated/fotografias'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedOperacionesRouteImport } from './routes/_authenticated/operaciones'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated/reportes'
import { Route as AuthenticatedSupervisoresRouteImport } from './routes/_authenticated/supervisores'
import { Route as AuthenticatedAdministracionIndexRouteImport } from './routes/_authenticated/administracion.index'
import { Route as AuthenticatedAdministracionCobrarRouteImport } from './routes/_authenticated/administracion.cobrar'
import { Route as AuthenticatedAdministracionEeccRouteImport } from './routes/_authenticated/administracion.eecc'
import { Route as AuthenticatedAdministracionPagarRouteImport } from './routes/_authenticated/administracion.pagar'
import { Route as AuthenticatedAdministracionReportesRouteImport } from './routes/_authenticated/administracion.reportes'
import { Route as AuthenticatedConfiguracionIndexRouteImport } from './routes/_authenticated/configuracion.index'
import { Route as AuthenticatedConfiguracionAuditoriaRouteImport } from './routes/_authenticated/configuracion.auditoria'
import { Route as AuthenticatedConfiguracionEmpleadosRouteImport } from './routes/_authenticated/configuracion.empleados'
import { Route as AuthenticatedConfiguracionParametrosRouteImport } from './routes/_authenticated/configuracion.parametros'
import { Route as AuthenticatedConfiguracionRolesRouteImport } from './routes/_authenticated/configuracion.roles'
import { Route as AuthenticatedConfiguracionUsuariosRouteImport } from './routes/_authenticated/configuracion.usuarios'
import { Route as AuthenticatedConfiguracionVacacionesRouteImport } from './routes/_authenticated/configuracion.vacaciones'
import { Route as AuthenticatedSedesIndexRouteImport } from './routes/_authenticated/sedes.index'
import { Route as AuthenticatedSupervisoresIndexRouteImport } from './routes/_authenticated/supervisores.index'
import { Route as AuthenticatedSupervisoresAlertasRouteImport } from './routes/_authenticated/supervisores.alertas'
import { Route as AuthenticatedSupervisoresCajasRouteImport } from './routes/_authenticated/supervisores.cajas'
import { Route as AuthenticatedSupervisoresCierreRouteImport } from './routes/_authenticated/supervisores.cierre'
import { Route as AuthenticatedSupervisoresInventarioRouteImport } from './routes/_authenticated/supervisores.inventario'
import { Route as AuthenticatedSupervisoresOperativoRouteImport } from './routes/_authenticated/supervisores.operativo'
import { Route as AuthenticatedSupervisoresPrediccionesRouteImport } from './routes/_authenticated/supervisores.predicciones'
import { Route as AuthenticatedSupervisoresPuntosVentaRouteImport } from './routes/_authenticated/supervisores.puntos-venta'
import { Route as AuthenticatedSupervisoresReportesRouteImport } from './routes/_authenticated/supervisores.reportes'
import { Route as AuthenticatedSupervisoresVentasRouteImport } from './routes/_authenticated/supervisores.ventas'
import { Route as AuthenticatedAdministracionReportesIndexRouteImport } from './routes/_authenticated/administracion.reportes.index'
import { Route as AuthenticatedAdministracionReportesFacturasRouteImport } from './routes/_authenticated/administracion.reportes.facturas'
import { Route as AuthenticatedSedesLocationIdIndexRouteImport } from './routes/_authenticated/sedes.$locationId.index'
import { Route as ApiPublicInvoicesIngestRouteImport } from './routes/api/public/invoices/ingest'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'
import { Route as AuthenticatedSedesLocationIdPosPosIdRouteImport } from './routes/_authenticated/sedes.$locationId.pos.$posId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdministracionRoute =
  AuthenticatedAdministracionRouteImport.update({
    id: '/administracion',
    path: '/administracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFotografiasRoute =
  AuthenticatedFotografiasRouteImport.update({
    id: '/fotografias',
    path: '/fotografias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperacionesRoute =
  AuthenticatedOperacionesRouteImport.update({
    id: '/operaciones',
    path: '/operaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupervisoresRoute =
  AuthenticatedSupervisoresRouteImport.update({
    id: '/supervisores',
    path: '/supervisores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracionIndexRoute =
  AuthenticatedAdministracionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdministracionRoute,
  } as any)
const AuthenticatedAdministracionCobrarRoute =
  AuthenticatedAdministracionCobrarRouteImport.update({
    id: '/cobrar',
    path: '/cobrar',
    getParentRoute: () => AuthenticatedAdministracionRoute,
  } as any)
const AuthenticatedAdministracionEeccRoute =
  AuthenticatedAdministracionEeccRouteImport.update({
    id: '/eecc',
    path: '/eecc',
    getParentRoute: () => AuthenticatedAdministracionRoute,
  } as any)
const AuthenticatedAdministracionPagarRoute =
  AuthenticatedAdministracionPagarRouteImport.update({
    id: '/pagar',
    path: '/pagar',
    getParentRoute: () => AuthenticatedAdministracionRoute,
  } as any)
const AuthenticatedAdministracionReportesRoute =
  AuthenticatedAdministracionReportesRouteImport.update({
    id: '/reportes',
    path: '/reportes',
    getParentRoute: () => AuthenticatedAdministracionRoute,
  } as any)
const AuthenticatedConfiguracionIndexRoute =
  AuthenticatedConfiguracionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConfiguracionRoute,
  } as any)
const AuthenticatedConfiguracionAuditoriaRoute =
  AuthenticatedConfiguracionAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedConfiguracionRoute,
  } as any)
const AuthenticatedConfiguracionEmpleadosRoute =
  AuthenticatedConfiguracionEmpleadosRouteImport.update({
    id: '/empleados',
    path: '/empleados',
    getParentRoute: () => AuthenticatedConfiguracionRoute,
  } as any)
const AuthenticatedConfiguracionParametrosRoute =
  AuthenticatedConfiguracionParametrosRouteImport.update({
    id: '/parametros',
    path: '/parametros',
    getParentRoute: () => AuthenticatedConfiguracionRoute,
  } as any)
const AuthenticatedConfiguracionRolesRoute =
  AuthenticatedConfiguracionRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AuthenticatedConfiguracionRoute,
  } as any)
const AuthenticatedConfiguracionUsuariosRoute =
  AuthenticatedConfiguracionUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedConfiguracionRoute,
  } as any)
const AuthenticatedConfiguracionVacacionesRoute =
  AuthenticatedConfiguracionVacacionesRouteImport.update({
    id: '/vacaciones',
    path: '/vacaciones',
    getParentRoute: () => AuthenticatedConfiguracionRoute,
  } as any)
const AuthenticatedSedesIndexRoute = AuthenticatedSedesIndexRouteImport.update({
  id: '/sedes/',
  path: '/sedes/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupervisoresIndexRoute =
  AuthenticatedSupervisoresIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSupervisoresRoute,
  } as any)
const AuthenticatedSupervisoresAlertasRoute =
  AuthenticatedSupervisoresAlertasRouteImport.update({
    id: '/alertas',
    path: '/alertas',
    getParentRoute: () => AuthenticatedSupervisoresRoute,
  } as any)
const AuthenticatedSupervisoresCajasRoute =
  AuthenticatedSupervisoresCajasRouteImport.update({
    id: '/cajas',
    path: '/cajas',
    getParentRoute: () => AuthenticatedSupervisoresRoute,
  } as any)
const AuthenticatedSupervisoresCierreRoute =
  AuthenticatedSupervisoresCierreRouteImport.update({
    id: '/cierre',
    path: '/cierre',
    getParentRoute: () => AuthenticatedSupervisoresRoute,
  } as any)
const AuthenticatedSupervisoresInventarioRoute =
  AuthenticatedSupervisoresInventarioRouteImport.update({
    id: '/inventario',
    path: '/inventario',
    getParentRoute: () => AuthenticatedSupervisoresRoute,
  } as any)
const AuthenticatedSupervisoresOperativoRoute =
  AuthenticatedSupervisoresOperativoRouteImport.update({
    id: '/operativo',
    path: '/operativo',
    getParentRoute: () => AuthenticatedSupervisoresRoute,
  } as any)
const AuthenticatedSupervisoresPrediccionesRoute =
  AuthenticatedSupervisoresPrediccionesRouteImport.update({
    id: '/predicciones',
    path: '/predicciones',
    getParentRoute: () => AuthenticatedSupervisoresRoute,
  } as any)
const AuthenticatedSupervisoresPuntosVentaRoute =
  AuthenticatedSupervisoresPuntosVentaRouteImport.update({
    id: '/puntos-venta',
    path: '/puntos-venta',
    getParentRoute: () => AuthenticatedSupervisoresRoute,
  } as any)
const AuthenticatedSupervisoresReportesRoute =
  AuthenticatedSupervisoresReportesRouteImport.update({
    id: '/reportes',
    path: '/reportes',
    getParentRoute: () => AuthenticatedSupervisoresRoute,
  } as any)
const AuthenticatedSupervisoresVentasRoute =
  AuthenticatedSupervisoresVentasRouteImport.update({
    id: '/ventas',
    path: '/ventas',
    getParentRoute: () => AuthenticatedSupervisoresRoute,
  } as any)
const AuthenticatedAdministracionReportesIndexRoute =
  AuthenticatedAdministracionReportesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdministracionReportesRoute,
  } as any)
const AuthenticatedAdministracionReportesFacturasRoute =
  AuthenticatedAdministracionReportesFacturasRouteImport.update({
    id: '/facturas',
    path: '/facturas',
    getParentRoute: () => AuthenticatedAdministracionReportesRoute,
  } as any)
const AuthenticatedSedesLocationIdIndexRoute =
  AuthenticatedSedesLocationIdIndexRouteImport.update({
    id: '/sedes/$locationId/',
    path: '/sedes/$locationId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicInvoicesIngestRoute = ApiPublicInvoicesIngestRouteImport.update({
  id: '/api/public/invoices/ingest',
  path: '/api/public/invoices/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSedesLocationIdPosPosIdRoute =
  AuthenticatedSedesLocationIdPosPosIdRouteImport.update({
    id: '/sedes/$locationId/pos/$posId',
    path: '/sedes/$locationId/pos/$posId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/administracion': typeof AuthenticatedAdministracionRouteWithChildren
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracion': typeof AuthenticatedConfiguracionRouteWithChildren
  '/fotografias': typeof AuthenticatedFotografiasRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/operaciones': typeof AuthenticatedOperacionesRoute
  '/pos': typeof AuthenticatedPosRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/supervisores': typeof AuthenticatedSupervisoresRouteWithChildren
  '/administracion/cobrar': typeof AuthenticatedAdministracionCobrarRoute
  '/administracion/eecc': typeof AuthenticatedAdministracionEeccRoute
  '/administracion/pagar': typeof AuthenticatedAdministracionPagarRoute
  '/administracion/reportes': typeof AuthenticatedAdministracionReportesRouteWithChildren
  '/configuracion/auditoria': typeof AuthenticatedConfiguracionAuditoriaRoute
  '/configuracion/empleados': typeof AuthenticatedConfiguracionEmpleadosRoute
  '/configuracion/parametros': typeof AuthenticatedConfiguracionParametrosRoute
  '/configuracion/roles': typeof AuthenticatedConfiguracionRolesRoute
  '/configuracion/usuarios': typeof AuthenticatedConfiguracionUsuariosRoute
  '/configuracion/vacaciones': typeof AuthenticatedConfiguracionVacacionesRoute
  '/supervisores/alertas': typeof AuthenticatedSupervisoresAlertasRoute
  '/supervisores/cajas': typeof AuthenticatedSupervisoresCajasRoute
  '/supervisores/cierre': typeof AuthenticatedSupervisoresCierreRoute
  '/supervisores/inventario': typeof AuthenticatedSupervisoresInventarioRoute
  '/supervisores/operativo': typeof AuthenticatedSupervisoresOperativoRoute
  '/supervisores/predicciones': typeof AuthenticatedSupervisoresPrediccionesRoute
  '/supervisores/puntos-venta': typeof AuthenticatedSupervisoresPuntosVentaRoute
  '/supervisores/reportes': typeof AuthenticatedSupervisoresReportesRoute
  '/supervisores/ventas': typeof AuthenticatedSupervisoresVentasRoute
  '/administracion/': typeof AuthenticatedAdministracionIndexRoute
  '/configuracion/': typeof AuthenticatedConfiguracionIndexRoute
  '/sedes/': typeof AuthenticatedSedesIndexRoute
  '/supervisores/': typeof AuthenticatedSupervisoresIndexRoute
  '/administracion/reportes/facturas': typeof AuthenticatedAdministracionReportesFacturasRoute
  '/api/public/invoices/ingest': typeof ApiPublicInvoicesIngestRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/administracion/reportes/': typeof AuthenticatedAdministracionReportesIndexRoute
  '/sedes/$locationId/': typeof AuthenticatedSedesLocationIdIndexRoute
  '/sedes/$locationId/pos/$posId': typeof AuthenticatedSedesLocationIdPosPosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/fotografias': typeof AuthenticatedFotografiasRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/operaciones': typeof AuthenticatedOperacionesRoute
  '/pos': typeof AuthenticatedPosRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/administracion/cobrar': typeof AuthenticatedAdministracionCobrarRoute
  '/administracion/eecc': typeof AuthenticatedAdministracionEeccRoute
  '/administracion/pagar': typeof AuthenticatedAdministracionPagarRoute
  '/configuracion/auditoria': typeof AuthenticatedConfiguracionAuditoriaRoute
  '/configuracion/empleados': typeof AuthenticatedConfiguracionEmpleadosRoute
  '/configuracion/parametros': typeof AuthenticatedConfiguracionParametrosRoute
  '/configuracion/roles': typeof AuthenticatedConfiguracionRolesRoute
  '/configuracion/usuarios': typeof AuthenticatedConfiguracionUsuariosRoute
  '/configuracion/vacaciones': typeof AuthenticatedConfiguracionVacacionesRoute
  '/supervisores/alertas': typeof AuthenticatedSupervisoresAlertasRoute
  '/supervisores/cajas': typeof AuthenticatedSupervisoresCajasRoute
  '/supervisores/cierre': typeof AuthenticatedSupervisoresCierreRoute
  '/supervisores/inventario': typeof AuthenticatedSupervisoresInventarioRoute
  '/supervisores/operativo': typeof AuthenticatedSupervisoresOperativoRoute
  '/supervisores/predicciones': typeof AuthenticatedSupervisoresPrediccionesRoute
  '/supervisores/puntos-venta': typeof AuthenticatedSupervisoresPuntosVentaRoute
  '/supervisores/reportes': typeof AuthenticatedSupervisoresReportesRoute
  '/supervisores/ventas': typeof AuthenticatedSupervisoresVentasRoute
  '/administracion': typeof AuthenticatedAdministracionIndexRoute
  '/configuracion': typeof AuthenticatedConfiguracionIndexRoute
  '/sedes': typeof AuthenticatedSedesIndexRoute
  '/supervisores': typeof AuthenticatedSupervisoresIndexRoute
  '/administracion/reportes/facturas': typeof AuthenticatedAdministracionReportesFacturasRoute
  '/api/public/invoices/ingest': typeof ApiPublicInvoicesIngestRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/administracion/reportes': typeof AuthenticatedAdministracionReportesIndexRoute
  '/sedes/$locationId': typeof AuthenticatedSedesLocationIdIndexRoute
  '/sedes/$locationId/pos/$posId': typeof AuthenticatedSedesLocationIdPosPosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/administracion': typeof AuthenticatedAdministracionRouteWithChildren
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRouteWithChildren
  '/_authenticated/fotografias': typeof AuthenticatedFotografiasRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/operaciones': typeof AuthenticatedOperacionesRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/_authenticated/supervisores': typeof AuthenticatedSupervisoresRouteWithChildren
  '/_authenticated/administracion/cobrar': typeof AuthenticatedAdministracionCobrarRoute
  '/_authenticated/administracion/eecc': typeof AuthenticatedAdministracionEeccRoute
  '/_authenticated/administracion/pagar': typeof AuthenticatedAdministracionPagarRoute
  '/_authenticated/administracion/reportes': typeof AuthenticatedAdministracionReportesRouteWithChildren
  '/_authenticated/configuracion/auditoria': typeof AuthenticatedConfiguracionAuditoriaRoute
  '/_authenticated/configuracion/empleados': typeof AuthenticatedConfiguracionEmpleadosRoute
  '/_authenticated/configuracion/parametros': typeof AuthenticatedConfiguracionParametrosRoute
  '/_authenticated/configuracion/roles': typeof AuthenticatedConfiguracionRolesRoute
  '/_authenticated/configuracion/usuarios': typeof AuthenticatedConfiguracionUsuariosRoute
  '/_authenticated/configuracion/vacaciones': typeof AuthenticatedConfiguracionVacacionesRoute
  '/_authenticated/supervisores/alertas': typeof AuthenticatedSupervisoresAlertasRoute
  '/_authenticated/supervisores/cajas': typeof AuthenticatedSupervisoresCajasRoute
  '/_authenticated/supervisores/cierre': typeof AuthenticatedSupervisoresCierreRoute
  '/_authenticated/supervisores/inventario': typeof AuthenticatedSupervisoresInventarioRoute
  '/_authenticated/supervisores/operativo': typeof AuthenticatedSupervisoresOperativoRoute
  '/_authenticated/supervisores/predicciones': typeof AuthenticatedSupervisoresPrediccionesRoute
  '/_authenticated/supervisores/puntos-venta': typeof AuthenticatedSupervisoresPuntosVentaRoute
  '/_authenticated/supervisores/reportes': typeof AuthenticatedSupervisoresReportesRoute
  '/_authenticated/supervisores/ventas': typeof AuthenticatedSupervisoresVentasRoute
  '/_authenticated/administracion/': typeof AuthenticatedAdministracionIndexRoute
  '/_authenticated/configuracion/': typeof AuthenticatedConfiguracionIndexRoute
  '/_authenticated/sedes/': typeof AuthenticatedSedesIndexRoute
  '/_authenticated/supervisores/': typeof AuthenticatedSupervisoresIndexRoute
  '/_authenticated/administracion/reportes/facturas': typeof AuthenticatedAdministracionReportesFacturasRoute
  '/api/public/invoices/ingest': typeof ApiPublicInvoicesIngestRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/_authenticated/administracion/reportes/': typeof AuthenticatedAdministracionReportesIndexRoute
  '/_authenticated/sedes/$locationId/': typeof AuthenticatedSedesLocationIdIndexRoute
  '/_authenticated/sedes/$locationId/pos/$posId': typeof AuthenticatedSedesLocationIdPosPosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/administracion'
    | '/clientes'
    | '/configuracion'
    | '/fotografias'
    | '/inicio'
    | '/inventario'
    | '/operaciones'
    | '/pos'
    | '/reportes'
    | '/supervisores'
    | '/administracion/cobrar'
    | '/administracion/eecc'
    | '/administracion/pagar'
    | '/administracion/reportes'
    | '/configuracion/auditoria'
    | '/configuracion/empleados'
    | '/configuracion/parametros'
    | '/configuracion/roles'
    | '/configuracion/usuarios'
    | '/configuracion/vacaciones'
    | '/supervisores/alertas'
    | '/supervisores/cajas'
    | '/supervisores/cierre'
    | '/supervisores/inventario'
    | '/supervisores/operativo'
    | '/supervisores/predicciones'
    | '/supervisores/puntos-venta'
    | '/supervisores/reportes'
    | '/supervisores/ventas'
    | '/administracion/'
    | '/configuracion/'
    | '/sedes/'
    | '/supervisores/'
    | '/administracion/reportes/facturas'
    | '/api/public/invoices/ingest'
    | '/api/public/webhooks/mercadopago'
    | '/administracion/reportes/'
    | '/sedes/$locationId/'
    | '/sedes/$locationId/pos/$posId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clientes'
    | '/fotografias'
    | '/inicio'
    | '/inventario'
    | '/operaciones'
    | '/pos'
    | '/reportes'
    | '/administracion/cobrar'
    | '/administracion/eecc'
    | '/administracion/pagar'
    | '/configuracion/auditoria'
    | '/configuracion/empleados'
    | '/configuracion/parametros'
    | '/configuracion/roles'
    | '/configuracion/usuarios'
    | '/configuracion/vacaciones'
    | '/supervisores/alertas'
    | '/supervisores/cajas'
    | '/supervisores/cierre'
    | '/supervisores/inventario'
    | '/supervisores/operativo'
    | '/supervisores/predicciones'
    | '/supervisores/puntos-venta'
    | '/supervisores/reportes'
    | '/supervisores/ventas'
    | '/administracion'
    | '/configuracion'
    | '/sedes'
    | '/supervisores'
    | '/administracion/reportes/facturas'
    | '/api/public/invoices/ingest'
    | '/api/public/webhooks/mercadopago'
    | '/administracion/reportes'
    | '/sedes/$locationId'
    | '/sedes/$locationId/pos/$posId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/administracion'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracion'
    | '/_authenticated/fotografias'
    | '/_authenticated/inicio'
    | '/_authenticated/inventario'
    | '/_authenticated/operaciones'
    | '/_authenticated/pos'
    | '/_authenticated/reportes'
    | '/_authenticated/supervisores'
    | '/_authenticated/administracion/cobrar'
    | '/_authenticated/administracion/eecc'
    | '/_authenticated/administracion/pagar'
    | '/_authenticated/administracion/reportes'
    | '/_authenticated/configuracion/auditoria'
    | '/_authenticated/configuracion/empleados'
    | '/_authenticated/configuracion/parametros'
    | '/_authenticated/configuracion/roles'
    | '/_authenticated/configuracion/usuarios'
    | '/_authenticated/configuracion/vacaciones'
    | '/_authenticated/supervisores/alertas'
    | '/_authenticated/supervisores/cajas'
    | '/_authenticated/supervisores/cierre'
    | '/_authenticated/supervisores/inventario'
    | '/_authenticated/supervisores/operativo'
    | '/_authenticated/supervisores/predicciones'
    | '/_authenticated/supervisores/puntos-venta'
    | '/_authenticated/supervisores/reportes'
    | '/_authenticated/supervisores/ventas'
    | '/_authenticated/administracion/'
    | '/_authenticated/configuracion/'
    | '/_authenticated/sedes/'
    | '/_authenticated/supervisores/'
    | '/_authenticated/administracion/reportes/facturas'
    | '/api/public/invoices/ingest'
    | '/api/public/webhooks/mercadopago'
    | '/_authenticated/administracion/reportes/'
    | '/_authenticated/sedes/$locationId/'
    | '/_authenticated/sedes/$locationId/pos/$posId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicInvoicesIngestRoute: typeof ApiPublicInvoicesIngestRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/administracion': {
      id: '/_authenticated/administracion'
      path: '/administracion'
      fullPath: '/administracion'
      preLoaderRoute: typeof AuthenticatedAdministracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fotografias': {
      id: '/_authenticated/fotografias'
      path: '/fotografias'
      fullPath: '/fotografias'
      preLoaderRoute: typeof AuthenticatedFotografiasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operaciones': {
      id: '/_authenticated/operaciones'
      path: '/operaciones'
      fullPath: '/operaciones'
      preLoaderRoute: typeof AuthenticatedOperacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisores': {
      id: '/_authenticated/supervisores'
      path: '/supervisores'
      fullPath: '/supervisores'
      preLoaderRoute: typeof AuthenticatedSupervisoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracion/': {
      id: '/_authenticated/administracion/'
      path: '/'
      fullPath: '/administracion/'
      preLoaderRoute: typeof AuthenticatedAdministracionIndexRouteImport
      parentRoute: typeof AuthenticatedAdministracionRoute
    }
    '/_authenticated/administracion/cobrar': {
      id: '/_authenticated/administracion/cobrar'
      path: '/cobrar'
      fullPath: '/administracion/cobrar'
      preLoaderRoute: typeof AuthenticatedAdministracionCobrarRouteImport
      parentRoute: typeof AuthenticatedAdministracionRoute
    }
    '/_authenticated/administracion/eecc': {
      id: '/_authenticated/administracion/eecc'
      path: '/eecc'
      fullPath: '/administracion/eecc'
      preLoaderRoute: typeof AuthenticatedAdministracionEeccRouteImport
      parentRoute: typeof AuthenticatedAdministracionRoute
    }
    '/_authenticated/administracion/pagar': {
      id: '/_authenticated/administracion/pagar'
      path: '/pagar'
      fullPath: '/administracion/pagar'
      preLoaderRoute: typeof AuthenticatedAdministracionPagarRouteImport
      parentRoute: typeof AuthenticatedAdministracionRoute
    }
    '/_authenticated/administracion/reportes': {
      id: '/_authenticated/administracion/reportes'
      path: '/reportes'
      fullPath: '/administracion/reportes'
      preLoaderRoute: typeof AuthenticatedAdministracionReportesRouteImport
      parentRoute: typeof AuthenticatedAdministracionRoute
    }
    '/_authenticated/configuracion/': {
      id: '/_authenticated/configuracion/'
      path: '/'
      fullPath: '/configuracion/'
      preLoaderRoute: typeof AuthenticatedConfiguracionIndexRouteImport
      parentRoute: typeof AuthenticatedConfiguracionRoute
    }
    '/_authenticated/configuracion/auditoria': {
      id: '/_authenticated/configuracion/auditoria'
      path: '/auditoria'
      fullPath: '/configuracion/auditoria'
      preLoaderRoute: typeof AuthenticatedConfiguracionAuditoriaRouteImport
      parentRoute: typeof AuthenticatedConfiguracionRoute
    }
    '/_authenticated/configuracion/empleados': {
      id: '/_authenticated/configuracion/empleados'
      path: '/empleados'
      fullPath: '/configuracion/empleados'
      preLoaderRoute: typeof AuthenticatedConfiguracionEmpleadosRouteImport
      parentRoute: typeof AuthenticatedConfiguracionRoute
    }
    '/_authenticated/configuracion/parametros': {
      id: '/_authenticated/configuracion/parametros'
      path: '/parametros'
      fullPath: '/configuracion/parametros'
      preLoaderRoute: typeof AuthenticatedConfiguracionParametrosRouteImport
      parentRoute: typeof AuthenticatedConfiguracionRoute
    }
    '/_authenticated/configuracion/roles': {
      id: '/_authenticated/configuracion/roles'
      path: '/roles'
      fullPath: '/configuracion/roles'
      preLoaderRoute: typeof AuthenticatedConfiguracionRolesRouteImport
      parentRoute: typeof AuthenticatedConfiguracionRoute
    }
    '/_authenticated/configuracion/usuarios': {
      id: '/_authenticated/configuracion/usuarios'
      path: '/usuarios'
      fullPath: '/configuracion/usuarios'
      preLoaderRoute: typeof AuthenticatedConfiguracionUsuariosRouteImport
      parentRoute: typeof AuthenticatedConfiguracionRoute
    }
    '/_authenticated/configuracion/vacaciones': {
      id: '/_authenticated/configuracion/vacaciones'
      path: '/vacaciones'
      fullPath: '/configuracion/vacaciones'
      preLoaderRoute: typeof AuthenticatedConfiguracionVacacionesRouteImport
      parentRoute: typeof AuthenticatedConfiguracionRoute
    }
    '/_authenticated/sedes/': {
      id: '/_authenticated/sedes/'
      path: '/sedes'
      fullPath: '/sedes/'
      preLoaderRoute: typeof AuthenticatedSedesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisores/': {
      id: '/_authenticated/supervisores/'
      path: '/'
      fullPath: '/supervisores/'
      preLoaderRoute: typeof AuthenticatedSupervisoresIndexRouteImport
      parentRoute: typeof AuthenticatedSupervisoresRoute
    }
    '/_authenticated/supervisores/alertas': {
      id: '/_authenticated/supervisores/alertas'
      path: '/alertas'
      fullPath: '/supervisores/alertas'
      preLoaderRoute: typeof AuthenticatedSupervisoresAlertasRouteImport
      parentRoute: typeof AuthenticatedSupervisoresRoute
    }
    '/_authenticated/supervisores/cajas': {
      id: '/_authenticated/supervisores/cajas'
      path: '/cajas'
      fullPath: '/supervisores/cajas'
      preLoaderRoute: typeof AuthenticatedSupervisoresCajasRouteImport
      parentRoute: typeof AuthenticatedSupervisoresRoute
    }
    '/_authenticated/supervisores/cierre': {
      id: '/_authenticated/supervisores/cierre'
      path: '/cierre'
      fullPath: '/supervisores/cierre'
      preLoaderRoute: typeof AuthenticatedSupervisoresCierreRouteImport
      parentRoute: typeof AuthenticatedSupervisoresRoute
    }
    '/_authenticated/supervisores/inventario': {
      id: '/_authenticated/supervisores/inventario'
      path: '/inventario'
      fullPath: '/supervisores/inventario'
      preLoaderRoute: typeof AuthenticatedSupervisoresInventarioRouteImport
      parentRoute: typeof AuthenticatedSupervisoresRoute
    }
    '/_authenticated/supervisores/operativo': {
      id: '/_authenticated/supervisores/operativo'
      path: '/operativo'
      fullPath: '/supervisores/operativo'
      preLoaderRoute: typeof AuthenticatedSupervisoresOperativoRouteImport
      parentRoute: typeof AuthenticatedSupervisoresRoute
    }
    '/_authenticated/supervisores/predicciones': {
      id: '/_authenticated/supervisores/predicciones'
      path: '/predicciones'
      fullPath: '/supervisores/predicciones'
      preLoaderRoute: typeof AuthenticatedSupervisoresPrediccionesRouteImport
      parentRoute: typeof AuthenticatedSupervisoresRoute
    }
    '/_authenticated/supervisores/puntos-venta': {
      id: '/_authenticated/supervisores/puntos-venta'
      path: '/puntos-venta'
      fullPath: '/supervisores/puntos-venta'
      preLoaderRoute: typeof AuthenticatedSupervisoresPuntosVentaRouteImport
      parentRoute: typeof AuthenticatedSupervisoresRoute
    }
    '/_authenticated/supervisores/reportes': {
      id: '/_authenticated/supervisores/reportes'
      path: '/reportes'
      fullPath: '/supervisores/reportes'
      preLoaderRoute: typeof AuthenticatedSupervisoresReportesRouteImport
      parentRoute: typeof AuthenticatedSupervisoresRoute
    }
    '/_authenticated/supervisores/ventas': {
      id: '/_authenticated/supervisores/ventas'
      path: '/ventas'
      fullPath: '/supervisores/ventas'
      preLoaderRoute: typeof AuthenticatedSupervisoresVentasRouteImport
      parentRoute: typeof AuthenticatedSupervisoresRoute
    }
    '/_authenticated/administracion/reportes/': {
      id: '/_authenticated/administracion/reportes/'
      path: '/'
      fullPath: '/administracion/reportes/'
      preLoaderRoute: typeof AuthenticatedAdministracionReportesIndexRouteImport
      parentRoute: typeof AuthenticatedAdministracionReportesRoute
    }
    '/_authenticated/administracion/reportes/facturas': {
      id: '/_authenticated/administracion/reportes/facturas'
      path: '/facturas'
      fullPath: '/administracion/reportes/facturas'
      preLoaderRoute: typeof AuthenticatedAdministracionReportesFacturasRouteImport
      parentRoute: typeof AuthenticatedAdministracionReportesRoute
    }
    '/_authenticated/sedes/$locationId/': {
      id: '/_authenticated/sedes/$locationId/'
      path: '/sedes/$locationId'
      fullPath: '/sedes/$locationId/'
      preLoaderRoute: typeof AuthenticatedSedesLocationIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/invoices/ingest': {
      id: '/api/public/invoices/ingest'
      path: '/api/public/invoices/ingest'
      fullPath: '/api/public/invoices/ingest'
      preLoaderRoute: typeof ApiPublicInvoicesIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sedes/$locationId/pos/$posId': {
      id: '/_authenticated/sedes/$locationId/pos/$posId'
      path: '/sedes/$locationId/pos/$posId'
      fullPath: '/sedes/$locationId/pos/$posId'
      preLoaderRoute: typeof AuthenticatedSedesLocationIdPosPosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdministracionReportesRouteChildren {
  AuthenticatedAdministracionReportesFacturasRoute: typeof AuthenticatedAdministracionReportesFacturasRoute
  AuthenticatedAdministracionReportesIndexRoute: typeof AuthenticatedAdministracionReportesIndexRoute
}

const AuthenticatedAdministracionReportesRouteChildren: AuthenticatedAdministracionReportesRouteChildren =
  {
    AuthenticatedAdministracionReportesFacturasRoute:
      AuthenticatedAdministracionReportesFacturasRoute,
    AuthenticatedAdministracionReportesIndexRoute:
      AuthenticatedAdministracionReportesIndexRoute,
  }

const AuthenticatedAdministracionReportesRouteWithChildren =
  AuthenticatedAdministracionReportesRoute._addFileChildren(
    AuthenticatedAdministracionReportesRouteChildren,
  )

interface AuthenticatedAdministracionRouteChildren {
  AuthenticatedAdministracionCobrarRoute: typeof AuthenticatedAdministracionCobrarRoute
  AuthenticatedAdministracionEeccRoute: typeof AuthenticatedAdministracionEeccRoute
  AuthenticatedAdministracionPagarRoute: typeof AuthenticatedAdministracionPagarRoute
  AuthenticatedAdministracionReportesRoute: typeof AuthenticatedAdministracionReportesRouteWithChildren
  AuthenticatedAdministracionIndexRoute: typeof AuthenticatedAdministracionIndexRoute
}

const AuthenticatedAdministracionRouteChildren: AuthenticatedAdministracionRouteChildren =
  {
    AuthenticatedAdministracionCobrarRoute:
      AuthenticatedAdministracionCobrarRoute,
    AuthenticatedAdministracionEeccRoute: AuthenticatedAdministracionEeccRoute,
    AuthenticatedAdministracionPagarRoute:
      AuthenticatedAdministracionPagarRoute,
    AuthenticatedAdministracionReportesRoute:
      AuthenticatedAdministracionReportesRouteWithChildren,
    AuthenticatedAdministracionIndexRoute:
      AuthenticatedAdministracionIndexRoute,
  }

const AuthenticatedAdministracionRouteWithChildren =
  AuthenticatedAdministracionRoute._addFileChildren(
    AuthenticatedAdministracionRouteChildren,
  )

interface AuthenticatedConfiguracionRouteChildren {
  AuthenticatedConfiguracionAuditoriaRoute: typeof AuthenticatedConfiguracionAuditoriaRoute
  AuthenticatedConfiguracionEmpleadosRoute: typeof AuthenticatedConfiguracionEmpleadosRoute
  AuthenticatedConfiguracionParametrosRoute: typeof AuthenticatedConfiguracionParametrosRoute
  AuthenticatedConfiguracionRolesRoute: typeof AuthenticatedConfiguracionRolesRoute
  AuthenticatedConfiguracionUsuariosRoute: typeof AuthenticatedConfiguracionUsuariosRoute
  AuthenticatedConfiguracionVacacionesRoute: typeof AuthenticatedConfiguracionVacacionesRoute
  AuthenticatedConfiguracionIndexRoute: typeof AuthenticatedConfiguracionIndexRoute
}

const AuthenticatedConfiguracionRouteChildren: AuthenticatedConfiguracionRouteChildren =
  {
    AuthenticatedConfiguracionAuditoriaRoute:
      AuthenticatedConfiguracionAuditoriaRoute,
    AuthenticatedConfiguracionEmpleadosRoute:
      AuthenticatedConfiguracionEmpleadosRoute,
    AuthenticatedConfiguracionParametrosRoute:
      AuthenticatedConfiguracionParametrosRoute,
    AuthenticatedConfiguracionRolesRoute: AuthenticatedConfiguracionRolesRoute,
    AuthenticatedConfiguracionUsuariosRoute:
      AuthenticatedConfiguracionUsuariosRoute,
    AuthenticatedConfiguracionVacacionesRoute:
      AuthenticatedConfiguracionVacacionesRoute,
    AuthenticatedConfiguracionIndexRoute: AuthenticatedConfiguracionIndexRoute,
  }

const AuthenticatedConfiguracionRouteWithChildren =
  AuthenticatedConfiguracionRoute._addFileChildren(
    AuthenticatedConfiguracionRouteChildren,
  )

interface AuthenticatedSupervisoresRouteChildren {
  AuthenticatedSupervisoresAlertasRoute: typeof AuthenticatedSupervisoresAlertasRoute
  AuthenticatedSupervisoresCajasRoute: typeof AuthenticatedSupervisoresCajasRoute
  AuthenticatedSupervisoresCierreRoute: typeof AuthenticatedSupervisoresCierreRoute
  AuthenticatedSupervisoresInventarioRoute: typeof AuthenticatedSupervisoresInventarioRoute
  AuthenticatedSupervisoresOperativoRoute: typeof AuthenticatedSupervisoresOperativoRoute
  AuthenticatedSupervisoresPrediccionesRoute: typeof AuthenticatedSupervisoresPrediccionesRoute
  AuthenticatedSupervisoresPuntosVentaRoute: typeof AuthenticatedSupervisoresPuntosVentaRoute
  AuthenticatedSupervisoresReportesRoute: typeof AuthenticatedSupervisoresReportesRoute
  AuthenticatedSupervisoresVentasRoute: typeof AuthenticatedSupervisoresVentasRoute
  AuthenticatedSupervisoresIndexRoute: typeof AuthenticatedSupervisoresIndexRoute
}

const AuthenticatedSupervisoresRouteChildren: AuthenticatedSupervisoresRouteChildren =
  {
    AuthenticatedSupervisoresAlertasRoute:
      AuthenticatedSupervisoresAlertasRoute,
    AuthenticatedSupervisoresCajasRoute: AuthenticatedSupervisoresCajasRoute,
    AuthenticatedSupervisoresCierreRoute: AuthenticatedSupervisoresCierreRoute,
    AuthenticatedSupervisoresInventarioRoute:
      AuthenticatedSupervisoresInventarioRoute,
    AuthenticatedSupervisoresOperativoRoute:
      AuthenticatedSupervisoresOperativoRoute,
    AuthenticatedSupervisoresPrediccionesRoute:
      AuthenticatedSupervisoresPrediccionesRoute,
    AuthenticatedSupervisoresPuntosVentaRoute:
      AuthenticatedSupervisoresPuntosVentaRoute,
    AuthenticatedSupervisoresReportesRoute:
      AuthenticatedSupervisoresReportesRoute,
    AuthenticatedSupervisoresVentasRoute: AuthenticatedSupervisoresVentasRoute,
    AuthenticatedSupervisoresIndexRoute: AuthenticatedSupervisoresIndexRoute,
  }

const AuthenticatedSupervisoresRouteWithChildren =
  AuthenticatedSupervisoresRoute._addFileChildren(
    AuthenticatedSupervisoresRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdministracionRoute: typeof AuthenticatedAdministracionRouteWithChildren
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRouteWithChildren
  AuthenticatedFotografiasRoute: typeof AuthenticatedFotografiasRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedOperacionesRoute: typeof AuthenticatedOperacionesRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedSupervisoresRoute: typeof AuthenticatedSupervisoresRouteWithChildren
  AuthenticatedSedesIndexRoute: typeof AuthenticatedSedesIndexRoute
  AuthenticatedSedesLocationIdIndexRoute: typeof AuthenticatedSedesLocationIdIndexRoute
  AuthenticatedSedesLocationIdPosPosIdRoute: typeof AuthenticatedSedesLocationIdPosPosIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdministracionRoute:
    AuthenticatedAdministracionRouteWithChildren,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRouteWithChildren,
  AuthenticatedFotografiasRoute: AuthenticatedFotografiasRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedOperacionesRoute: AuthenticatedOperacionesRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedSupervisoresRoute: AuthenticatedSupervisoresRouteWithChildren,
  AuthenticatedSedesIndexRoute: AuthenticatedSedesIndexRoute,
  AuthenticatedSedesLocationIdIndexRoute:
    AuthenticatedSedesLocationIdIndexRoute,
  AuthenticatedSedesLocationIdPosPosIdRoute:
    AuthenticatedSedesLocationIdPosPosIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicInvoicesIngestRoute: ApiPublicInvoicesIngestRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
