/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdministracionRouteImport } from './routes/_authenticated/administracion'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedFotografiasRouteImport } from './routes/_authenticated/fotografias'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedOperacionesRouteImport } from './routes/_authenticated/operaciones'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated/reportes'
import { Route as AuthenticatedConfiguracionIndexRouteImport } from './routes/_authenticated/configuracion.index'
import { Route as AuthenticatedConfiguracionUsuariosRouteImport } from './routes/_authenticated/configuracion.usuarios'
import { Route as AuthenticatedSedesIndexRouteImport } from './routes/_authenticated/sedes.index'
import { Route as AuthenticatedSedesLocationIdIndexRouteImport } from './routes/_authenticated/sedes.$locationId.index'
import { Route as ApiPublicInvoicesIngestRouteImport } from './routes/api/public/invoices/ingest'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'
import { Route as AuthenticatedSedesLocationIdPosPosIdRouteImport } from './routes/_authenticated/sedes.$locationId.pos.$posId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdministracionRoute =
  AuthenticatedAdministracionRouteImport.update({
    id: '/administracion',
    path: '/administracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFotografiasRoute =
  AuthenticatedFotografiasRouteImport.update({
    id: '/fotografias',
    path: '/fotografias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperacionesRoute =
  AuthenticatedOperacionesRouteImport.update({
    id: '/operaciones',
    path: '/operaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracionIndexRoute =
  AuthenticatedConfiguracionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConfiguracionRoute,
  } as any)
const AuthenticatedConfiguracionUsuariosRoute =
  AuthenticatedConfiguracionUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedConfiguracionRoute,
  } as any)
const AuthenticatedSedesIndexRoute = AuthenticatedSedesIndexRouteImport.update({
  id: '/sedes/',
  path: '/sedes/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSedesLocationIdIndexRoute =
  AuthenticatedSedesLocationIdIndexRouteImport.update({
    id: '/sedes/$locationId/',
    path: '/sedes/$locationId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicInvoicesIngestRoute = ApiPublicInvoicesIngestRouteImport.update({
  id: '/api/public/invoices/ingest',
  path: '/api/public/invoices/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSedesLocationIdPosPosIdRoute =
  AuthenticatedSedesLocationIdPosPosIdRouteImport.update({
    id: '/sedes/$locationId/pos/$posId',
    path: '/sedes/$locationId/pos/$posId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/administracion': typeof AuthenticatedAdministracionRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracion': typeof AuthenticatedConfiguracionRouteWithChildren
  '/fotografias': typeof AuthenticatedFotografiasRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/operaciones': typeof AuthenticatedOperacionesRoute
  '/pos': typeof AuthenticatedPosRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/configuracion/usuarios': typeof AuthenticatedConfiguracionUsuariosRoute
  '/configuracion/': typeof AuthenticatedConfiguracionIndexRoute
  '/sedes/': typeof AuthenticatedSedesIndexRoute
  '/api/public/invoices/ingest': typeof ApiPublicInvoicesIngestRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/sedes/$locationId/': typeof AuthenticatedSedesLocationIdIndexRoute
  '/sedes/$locationId/pos/$posId': typeof AuthenticatedSedesLocationIdPosPosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/administracion': typeof AuthenticatedAdministracionRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/fotografias': typeof AuthenticatedFotografiasRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/operaciones': typeof AuthenticatedOperacionesRoute
  '/pos': typeof AuthenticatedPosRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/configuracion/usuarios': typeof AuthenticatedConfiguracionUsuariosRoute
  '/configuracion': typeof AuthenticatedConfiguracionIndexRoute
  '/sedes': typeof AuthenticatedSedesIndexRoute
  '/api/public/invoices/ingest': typeof ApiPublicInvoicesIngestRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/sedes/$locationId': typeof AuthenticatedSedesLocationIdIndexRoute
  '/sedes/$locationId/pos/$posId': typeof AuthenticatedSedesLocationIdPosPosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/administracion': typeof AuthenticatedAdministracionRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRouteWithChildren
  '/_authenticated/fotografias': typeof AuthenticatedFotografiasRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/operaciones': typeof AuthenticatedOperacionesRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/_authenticated/configuracion/usuarios': typeof AuthenticatedConfiguracionUsuariosRoute
  '/_authenticated/configuracion/': typeof AuthenticatedConfiguracionIndexRoute
  '/_authenticated/sedes/': typeof AuthenticatedSedesIndexRoute
  '/api/public/invoices/ingest': typeof ApiPublicInvoicesIngestRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/_authenticated/sedes/$locationId/': typeof AuthenticatedSedesLocationIdIndexRoute
  '/_authenticated/sedes/$locationId/pos/$posId': typeof AuthenticatedSedesLocationIdPosPosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/administracion'
    | '/clientes'
    | '/configuracion'
    | '/fotografias'
    | '/inicio'
    | '/inventario'
    | '/operaciones'
    | '/pos'
    | '/reportes'
    | '/configuracion/usuarios'
    | '/configuracion/'
    | '/sedes/'
    | '/api/public/invoices/ingest'
    | '/api/public/webhooks/mercadopago'
    | '/sedes/$locationId/'
    | '/sedes/$locationId/pos/$posId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/administracion'
    | '/clientes'
    | '/fotografias'
    | '/inicio'
    | '/inventario'
    | '/operaciones'
    | '/pos'
    | '/reportes'
    | '/configuracion/usuarios'
    | '/configuracion'
    | '/sedes'
    | '/api/public/invoices/ingest'
    | '/api/public/webhooks/mercadopago'
    | '/sedes/$locationId'
    | '/sedes/$locationId/pos/$posId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/administracion'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracion'
    | '/_authenticated/fotografias'
    | '/_authenticated/inicio'
    | '/_authenticated/inventario'
    | '/_authenticated/operaciones'
    | '/_authenticated/pos'
    | '/_authenticated/reportes'
    | '/_authenticated/configuracion/usuarios'
    | '/_authenticated/configuracion/'
    | '/_authenticated/sedes/'
    | '/api/public/invoices/ingest'
    | '/api/public/webhooks/mercadopago'
    | '/_authenticated/sedes/$locationId/'
    | '/_authenticated/sedes/$locationId/pos/$posId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicInvoicesIngestRoute: typeof ApiPublicInvoicesIngestRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/administracion': {
      id: '/_authenticated/administracion'
      path: '/administracion'
      fullPath: '/administracion'
      preLoaderRoute: typeof AuthenticatedAdministracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fotografias': {
      id: '/_authenticated/fotografias'
      path: '/fotografias'
      fullPath: '/fotografias'
      preLoaderRoute: typeof AuthenticatedFotografiasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operaciones': {
      id: '/_authenticated/operaciones'
      path: '/operaciones'
      fullPath: '/operaciones'
      preLoaderRoute: typeof AuthenticatedOperacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion/': {
      id: '/_authenticated/configuracion/'
      path: '/'
      fullPath: '/configuracion/'
      preLoaderRoute: typeof AuthenticatedConfiguracionIndexRouteImport
      parentRoute: typeof AuthenticatedConfiguracionRoute
    }
    '/_authenticated/configuracion/usuarios': {
      id: '/_authenticated/configuracion/usuarios'
      path: '/usuarios'
      fullPath: '/configuracion/usuarios'
      preLoaderRoute: typeof AuthenticatedConfiguracionUsuariosRouteImport
      parentRoute: typeof AuthenticatedConfiguracionRoute
    }
    '/_authenticated/sedes/': {
      id: '/_authenticated/sedes/'
      path: '/sedes'
      fullPath: '/sedes/'
      preLoaderRoute: typeof AuthenticatedSedesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sedes/$locationId/': {
      id: '/_authenticated/sedes/$locationId/'
      path: '/sedes/$locationId'
      fullPath: '/sedes/$locationId/'
      preLoaderRoute: typeof AuthenticatedSedesLocationIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/invoices/ingest': {
      id: '/api/public/invoices/ingest'
      path: '/api/public/invoices/ingest'
      fullPath: '/api/public/invoices/ingest'
      preLoaderRoute: typeof ApiPublicInvoicesIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sedes/$locationId/pos/$posId': {
      id: '/_authenticated/sedes/$locationId/pos/$posId'
      path: '/sedes/$locationId/pos/$posId'
      fullPath: '/sedes/$locationId/pos/$posId'
      preLoaderRoute: typeof AuthenticatedSedesLocationIdPosPosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedConfiguracionRouteChildren {
  AuthenticatedConfiguracionUsuariosRoute: typeof AuthenticatedConfiguracionUsuariosRoute
  AuthenticatedConfiguracionIndexRoute: typeof AuthenticatedConfiguracionIndexRoute
}

const AuthenticatedConfiguracionRouteChildren: AuthenticatedConfiguracionRouteChildren =
  {
    AuthenticatedConfiguracionUsuariosRoute:
      AuthenticatedConfiguracionUsuariosRoute,
    AuthenticatedConfiguracionIndexRoute: AuthenticatedConfiguracionIndexRoute,
  }

const AuthenticatedConfiguracionRouteWithChildren =
  AuthenticatedConfiguracionRoute._addFileChildren(
    AuthenticatedConfiguracionRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdministracionRoute: typeof AuthenticatedAdministracionRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRouteWithChildren
  AuthenticatedFotografiasRoute: typeof AuthenticatedFotografiasRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedOperacionesRoute: typeof AuthenticatedOperacionesRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedSedesIndexRoute: typeof AuthenticatedSedesIndexRoute
  AuthenticatedSedesLocationIdIndexRoute: typeof AuthenticatedSedesLocationIdIndexRoute
  AuthenticatedSedesLocationIdPosPosIdRoute: typeof AuthenticatedSedesLocationIdPosPosIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdministracionRoute: AuthenticatedAdministracionRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRouteWithChildren,
  AuthenticatedFotografiasRoute: AuthenticatedFotografiasRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedOperacionesRoute: AuthenticatedOperacionesRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedSedesIndexRoute: AuthenticatedSedesIndexRoute,
  AuthenticatedSedesLocationIdIndexRoute:
    AuthenticatedSedesLocationIdIndexRoute,
  AuthenticatedSedesLocationIdPosPosIdRoute:
    AuthenticatedSedesLocationIdPosPosIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicInvoicesIngestRoute: ApiPublicInvoicesIngestRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
